[package]
name = "sling"
version = "1.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
bytes = "1"
log = { version = "0.4", features = ['std'] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

tokio = { version = "1", features = ["fs","sync","rt-multi-thread","process"] }
# tokio-stream = "0.1"
# futures = "0.3"

# env_logger = "0.10"

cln-rpc = "0.1.4"
cln-plugin = "0.1.5"
# cln-plugin = {path= "../lightning/plugins"}
# cln-rpc = {path= "../lightning/cln-rpc"}

tabled = "0.12"
num-format = "0.4"
struct-field-names-as-array = "0.2"
chrono = "0.4"
rand = "0.8"
parking_lot = "0.12"
bitcoin = "0.29"

log-panics = "2"

[target.'cfg(all(not(windows), not(target_env = "musl")))'.dependencies]
jemallocator = "0.5"
# [dev-dependencies]
# tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
# cln-grpc = "0.1"

[profile.release]
strip = true
codegen-units = 1
lto = "fat"
debug = false
